name: lhokride
description: "LhokRide+ - Layanan Transportasi Terbaik"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.4.0
  flutter_secure_storage: ^8.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  intl: ^0.18.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  url_launcher: ^6.1.7
  flutter_polyline_points: ^2.0.0
  shared_preferences: ^2.0.15
  timeago: ^3.3.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^19.2.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  flutter_svg: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_database: ^10.4.0
  provider: ^6.1.1 
  image_picker: ^0.8.7+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  install_plugin: ^2.1.0 # Untuk install APK langsung (hanya Android)
  dio: ^5.4.3+1
  app_settings: ^5.0.0
  marquee: ^2.2.3
  http_parser: ^4.0.2
  firebase_analytics: ^10.7.4
  flutter_map_marker_cluster: ^1.1.1
  app_state: 0.9.6 # Add this line
  cached_network_image: ^3.3.1
  animate_do: ^3.3.4 
  webview_flutter: ^4.2.2
  flutter_spinkit: ^5.2.0
  flutterfire_cli: ^1.3.1
  flutter_map_animations: ^0.6.0
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/logo.png" # ganti dengan path ikon kamu


flutter:
  assets:
    - assets/icons/
    - assets/maps/
    - assets/images/


  uses-material-design: true
