// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzOGNg2NG70Mz-jA3scTsbvLMQGdj3otE',
    appId: '1:883705090631:web:9f34c94862b5ff50221762',
    messagingSenderId: '883705090631',
    projectId: 'lhokrideplus-548c0',
    authDomain: 'lhokrideplus-548c0.firebaseapp.com',
    databaseURL:
        'https://lhokrideplus-548c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lhokrideplus-548c0.firebasestorage.app',
    measurementId: 'G-DMRQP6CG05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwG1nKxAaWe92PyWs-ybFIaKPP_mY61s',
    appId: '1:883705090631:android:3b9fb2fe54c01a9a221762',
    messagingSenderId: '883705090631',
    projectId: 'lhokrideplus-548c0',
    databaseURL:
        'https://lhokrideplus-548c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lhokrideplus-548c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMe7ejyJgPn1YwI467_Rt7D6sdgLePm8',
    appId: '1:883705090631:ios:b471ac1b42525070221762',
    messagingSenderId: '883705090631',
    projectId: 'lhokrideplus-548c0',
    databaseURL:
        'https://lhokrideplus-548c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lhokrideplus-548c0.firebasestorage.app',
    iosBundleId: 'com.lhokrideplus.lsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPMe7ejyJgPn1YwI467_Rt7D6sdgLePm8',
    appId: '1:883705090631:ios:b471ac1b42525070221762',
    messagingSenderId: '883705090631',
    projectId: 'lhokrideplus-548c0',
    databaseURL:
        'https://lhokrideplus-548c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lhokrideplus-548c0.firebasestorage.app',
    iosBundleId: 'com.lhokrideplus.lsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzOGNg2NG70Mz-jA3scTsbvLMQGdj3otE',
    appId: '1:883705090631:web:fdefcc55628d0524221762',
    messagingSenderId: '883705090631',
    projectId: 'lhokrideplus-548c0',
    authDomain: 'lhokrideplus-548c0.firebaseapp.com',
    databaseURL:
        'https://lhokrideplus-548c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lhokrideplus-548c0.firebasestorage.app',
    measurementId: 'G-B39FPLCM90',
  );
}
